# Generated by Django 3.0.2 on 2020-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubg_id', models.CharField(blank=True, max_length=9)),
                ('pubg_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
