# Generated by Django 3.0.2 on 2020-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_pubg_info_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubg_info',
            name='clan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pubg_info',
            name='mobile_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pubg_info',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
