# Generated by Django 3.0.2 on 2020-03-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200303_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='wirthdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=3)),
                ('paytm_no', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=20)),
            ],
        ),
    ]
