# Generated by Django 2.2.2 on 2020-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wirthdraw'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('pubg_id', models.CharField(blank=True, max_length=9)),
                ('pubg_name', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('age', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='pubg_info',
        ),
    ]
