# Generated by Django 2.2.2 on 2020-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200311_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pubg_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
