# Generated by Django 2.2.2 on 2020-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userdetails_pubg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='pubg_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
