# Generated by Django 3.0.2 on 2020-02-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=20)),
                ('match_type', models.CharField(max_length=5)),
                ('match_map', models.CharField(max_length=20)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('match_entry', models.IntegerField()),
                ('per_kill_prize', models.IntegerField()),
                ('winner_prize', models.IntegerField()),
            ],
        ),
    ]
