# Generated by Django 3.0.2 on 2020-02-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_pics',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
