# Generated by Django 3.0.2 on 2020-02-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0002_match_match_pics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('pubg_id', models.IntegerField()),
                ('Match_id', models.IntegerField()),
                ('match_name', models.CharField(max_length=20)),
                ('pubg_name', models.CharField(max_length=20)),
            ],
        ),
    ]
