# Generated by Django 3.0.2 on 2020-03-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0004_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='kill',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='join',
            name='win',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='match',
            name='room_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='room_pass',
            field=models.CharField(default='', max_length=10),
        ),
    ]
