# Generated by Django 3.0.2 on 2020-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0005_auto_20200303_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='kill',
            field=models.IntegerField(null=True),
        ),
    ]
