# Generated by Django 2.2.2 on 2020-03-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0007_auto_20200308_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('country', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='room_id',
            field=models.CharField(blank='True', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='room_pass',
            field=models.CharField(blank='True', default='', max_length=10),
        ),
    ]
