# Generated by Django 2.2.2 on 2020-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0008_auto_20200309_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='Email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='join',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
