# Generated by Django 2.2.2 on 2020-03-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0009_auto_20200311_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
