# Generated by Django 2.2.2 on 2020-03-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0009_auto_20200311_1906'),
    ]

    operations = [
        
    ]
