# Generated by Django 2.2.2 on 2020-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubg', '0010_join_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
